# Use the latest Node.js (or specify a custom version)
FROM node:20 AS base

# Set the working directory
WORKDIR /app

# Copy package.json and yarn.lock for dependency caching
COPY package.json yarn.lock ./

# Install dependencies using Yarn
RUN yarn install

# Copy the rest of the application code
COPY . .

# Expose the port for the development server
EXPOSE 8465

# Start the development server
CMD ["yarn", "start"]