version: '3.8'

services:
  file-server:
    build:
      context: ./file-server
    ports:
      - "8465:8465"
    volumes:
      - ./file-server/public:/app/public
      - ./file-server/temp:/app/temp
    env_file:
      - ./file-server/.env
    restart: unless-stopped

  messaging-server:
    build:
      context: ./messaging-server
    ports:
      - "8654:8654"
    env_file:
      - ./messaging-server/.env
    restart: unless-stopped

  webpage:
    build:
      context: ./webpage
    ports:
      - "8464:3000"
    env_file:
      - ./webpage/.env.local
    restart: unless-stopped
  
  db:
    image: postgres
    restart: always
    env_file:
      - ./webpage/.env.local
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
 
volumes:
  pgdata: