version: '3.8'

services:
  file-server:
    build:
      context: ./file-server
    ports:
      - "8465:8465"
    volumes:
      - ./file-server/public:/app/public
      - ./file-server/temp:/app/temp
    env_file:
      - ./file-server/.env
    restart: unless-stopped

  webpage:
    build:
      context: ./webpage
    ports:
      - "8464:3000"
    env_file:
      - ./webpage/.env.local
    restart: unless-stopped